### ISSUE TITLE
Found Trouble in  email-backup script

### ISSUE THREAD

**Issue by sunnychuchu** [eworm-de/routeros-scripts#12]
There are some issue in version 55. $SendEMail2 functions is unable to send out email in email-backup. will it be carry attachment issue in that function? Meanwhile $SendNotification2 can send out telegram , matrix and email. 
My version is 6.48.3

**Comment by eworm-de** [comment]
Just a stupid typo... Already fixed, please update again.
Thanks a lot for reporting! (And leave a star if you have not...)

**Comment by sunnychuchu** [comment]
thanks for quick response
