### ISSUE TITLE
:global MkDir;

### ISSUE THREAD

**Issue by sunnychuchu** [eworm-de/routeros-scripts#14]
Hi,

I have deployed about 10 pcs of router for different models , some of router is unable create email-backup folder when first run of script.   ![image](https://user-images.githubusercontent.com/85664048/122805289-7d8dc780-d2fb-11eb-8c48-cf41c8730ef7.png)
Once folder is created, all email-backup will run successfully on 2nd times and so on.

Sunny

**Comment by eworm-de** [comment]
Hmm, I have not see this to fail so far...

Ok, let's start with some details: RouterOS does not provide a lot of functionality regarding file handling. Creating directories is not implemented for example, so I have to use a workaround. That workaround is to enable the `www` service to listen on loopback address, then download a file to a path including the directory, finally removing the file which leaves the directory.

So I wonder...
* Did you have any special configuration for the `www` service?
* Please show output of `/ip service export`.
* Are there any firewall rules that block connections to loopback address?
* Also please check if any settings are altered (enabled with address `127.0.0.1/32` on port `80`) but not restored to the original settings.
* The second attempt succeeds or do you create the directory manually?
* Do the affected devices use a ram disk? Please show output of `/file print count-only where name="flash" type="disk"`.

**Comment by eworm-de** [comment]
Let's try something new, which should work with less trouble.
Can you try the changes in a424691a68dd2d0c12a979e58a5c95a21bdee1de (or `next` branch)?

**Comment by sunnychuchu** [comment]
It seem much better after using SMB method. I will perform more test on different model of MTK router. 
Thanks for your advancement 
Sunny

**Comment by eworm-de** [comment]
Just merged this into the `main` branch.
It works for me™️ and - though it is still a workaround - looks cleaner than what we had before. Thanks for the report!
