### ISSUE TITLE
Can you please add a health check script for http/https server?

### ISSUE THREAD

**Issue by elico** [eworm-de/routeros-scripts#16]
I have a local device which has a http endpoint flag ie: "http://10.200.191.200/works/"
When there is no response or the response is "disabled" then the device is down.
The device is expecting "load" more the 1 request per second and the response should not take more then 3 seconds.

Can you please write an example check for this use case?

**Comment by eworm-de** [comment]
I had a lot of thoughts about this, but was about to close this without implementing.
The fetch tool is a nice thing, but it is not as reliable as one would like it to be. Especially in case of failure it behaves really strange sometimes. Additionally getting any info about a failure is impossible.

But finally Mikrotik decided to extend [netwatch](https://help.mikrotik.com/docs/display/ROS/Netwatch), so it can do tcp and http probes now. You should configure that and use it with [Notify on host up and down](https://git.eworm.de/cgit/routeros-scripts/about/doc/netwatch-notify.md).

Sadly it is still kind of limit, especially you can not add a document uri in url or check https. Let's hope they will add that later... Please request on forum or (even better) open a support ticket.
