### ISSUE TITLE
$DownloadPackage not pulling packages

### ISSUE THREAD

**Issue by dd2594gh** [eworm-de/routeros-scripts#21]
$DownloadPackage failed to connect and pull packages. Issue is at line 261 in the global-functions.

The line reads:
:local PkgFile ($PkgName . "-" . $PkgVer . "-" . $PkgArch . ".npk");

Corrected line:
:local PkgFile ($PkgName . "-" . $PkgArch . "-" . $PkgVer . ".npk");

**Comment by eworm-de** [comment]
I am pretty sure it works just fine. At least it did to date. I will check later.

How do you invoke the function?

**Comment by dd2594gh** [comment]
$DownloadPackage routeros “6.49.2” miosbe routeros; 

In order to do initial download for use with the capstan-download-packages script

From what I see it does work with the check-routeros-update … so it may be isolated to the one spot — but I did verify by hand that the MikroTik website maps to the corrected line  and that the script does work once the line is changed

Thanks for the scripts — saving me a ton of time instead having to script on my own!

Sent from my iPhone

> On Jan 17, 2022, at 11:06 AM, Christian Hesse ***@***.***> wrote:
> 
> ﻿
> I am pretty sure it works just fine. At least it did to date. I will check later.
> 
> How do you invoke the function?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.



Power System Sentinel Technologies, LLC
101 Skyline Dr.
Warrior, AL 35180
(205) 631-3357

**Comment by eworm-de** [comment]
Ah, this is a special case I do not catch. I used to have split packages, so never tested. 😝

Have a look in `/ system package`... You will see that the package is named `routeros-mipsbe` there. The download succeeds with that package name:

```
$DownloadPackage routeros-mipsbe 6.49.2 mipsbe routeros;
```

This spacial case is now handled with 1e6931c8e34d5035cb07baa98b57eccbcd4278ab, so the download with your command should succeed as well:

```
$DownloadPackage routeros 6.49.2 mipsbe routeros;
```

Thanks for reporting this!

**Comment by dd2594gh** [comment]
Christian,


Many thanks - was wondering if that was not the case as the other updates as you said worked.


A quick question -- have you ever looked at or thought about where to add something to make the router do the firmware upgrade when doing the routeros upgrade?


Would it work to add a new global, set initially to a false condition. When the routeros upgrade is run, set the new global to a true condition, then on start if the new global is true execute the /system routerboard upgrade and reboot?



Thanks
Devin Dean
Test Director/Systems Administrator
(205) 631-3357 ext. 406
(205) 543-5551




 From:   Christian Hesse ***@***.***> 
 To:   eworm-de/routeros-scripts ***@***.***> 
 Cc:   dd2594gh ***@***.***>, Author ***@***.***> 
 Sent:   1/17/2022 1:56 PM 
 Subject:   EXTERNAL: Re: [eworm-de/routeros-scripts] $DownloadPackage not pulling packages (Issue #21) 


 
Ah, this is a special case I do not catch. I used to have split packages, so never tested. 😝 
Have a look in / system package... You will see that the package is named routeros-mipsbe there. The download succeeds with that package name: $DownloadPackage routeros-mipsbe 6.49.2 mipsbe routeros;

 
This spacial case is now handled with 1e6931c, so the download with your command should succeed as well: $DownloadPackage routeros 6.49.2 mipsbe routeros;

 
Thanks for reporting this! 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 


Power System Sentinel Technologies, LLC
101 Skyline Dr.
Warrior, AL 35180
(205) 631-3357

**Comment by eworm-de** [comment]
Well, you can make the update manually yourself or automatically by RouterOS. First does not need a script, for second just set:

```
/ system routerboard settings set auto-upgrade=yes
```

**Comment by dd2594gh** [comment]
You would still need to do a second reboot though - correct? That is the part I guess I am wanting to automate ... so if I set up a new global with default value "false" -- and then when a routeros update is run set it "true" .... then at startup look at that global - if "true" set it back to false and do another reboot?

Thanks for the assistance!
Devin Dean
Test Director/Systems Administrator
(205) 631-3357 ext. 406
(205) 543-5551




 From:   Christian Hesse ***@***.***> 
 To:   eworm-de/routeros-scripts ***@***.***> 
 Cc:   dd2594gh ***@***.***>, Author ***@***.***> 
 Sent:   1/17/2022 2:16 PM 
 Subject:   EXTERNAL: Re: [eworm-de/routeros-scripts] $DownloadPackage not pulling packages (Issue #21) 


 
Well, you can make the update manually yourself or automatically by RouterOS. First does not need a script, for second just set: / system routerboard settings set auto-upgrade=yes
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 


Power System Sentinel Technologies, LLC
101 Skyline Dr.
Warrior, AL 35180
(205) 631-3357

**Comment by eworm-de** [comment]
I do not think a global variable will help here... Variables do not survive a reboot.

You could create a scheduler the runs on startup, with this code:

```
:local RouterBoard [ / system routerboard get ];
:if ($RouterBoard->"current-firmware" != $RouterBoard->"upgrade-firmware" && \
     [ / system routerboard settings get auto-upgrade ] = true) do={
  / system reboot;
}
```

Is that what you want?

**Comment by dd2594gh** [comment]
I knew there was something I was missing!

Devin Dean
Test Director/Systems Administrator
(205) 631-3357 ext. 406
(205) 543-5551




 From:   Christian Hesse ***@***.***> 
 To:   eworm-de/routeros-scripts ***@***.***> 
 Cc:   dd2594gh ***@***.***>, Author ***@***.***> 
 Sent:   1/17/2022 2:36 PM 
 Subject:   EXTERNAL: Re: [eworm-de/routeros-scripts] $DownloadPackage not pulling packages (Issue #21) 


 
I do not think a global variable will help here... Variables do not survive a reboot. 
You could create a scheduler the runs on startup, with this code: :local RouterBoard [ / system routerboard get ];
:if ($RouterBoard->"current-firmware" != $RouterBoard->"upgrade-firmware" && \
     [ / system routerboard settings get auto-upgrade ] = true) do={
  / system reboot;
}
 
Is that what you want? 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 


Power System Sentinel Technologies, LLC
101 Skyline Dr.
Warrior, AL 35180
(205) 631-3357

**Comment by eworm-de** [comment]
Oh, probably you need a delay at the beginning... No idea how long it takes for the upgrade to finish. Rebooting too early results in a boot loop.

**Comment by dd2594gh** [comment]
Thanks - I will play with that when I get home this evening on my test CRS305

Devin Dean
Test Director/Systems Administrator
(205) 631-3357 ext. 406
(205) 543-5551




 From:   Christian Hesse ***@***.***> 
 To:   eworm-de/routeros-scripts ***@***.***> 
 Cc:   dd2594gh ***@***.***>, Author ***@***.***> 
 Sent:   1/17/2022 2:45 PM 
 Subject:   EXTERNAL: Re: [eworm-de/routeros-scripts] $DownloadPackage not pulling packages (Issue #21) 


 
Oh, probably you need a delay at the beginning... No idea how long it takes for the upgrade to finish. Rebooting too early results in a boot loop. 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 


Power System Sentinel Technologies, LLC
101 Skyline Dr.
Warrior, AL 35180
(205) 631-3357
