### ISSUE TITLE
How use script s with Netwatch ?

### ISSUE THREAD

**Issue by Jason-MK** [eworm-de/routeros-scripts#26]
Hello ,

I want to know how to use the scripts with Netwatch ?

I mean should I write the script ? there are no free scripts ?

I mean I want to have a script to send me a message where any GRE Tunnel is down for 1 second ?

I really need your help

Best Regards

**Comment by eworm-de** [comment]
Wait... What?! You want to act if a GRE tunnel is down for just a single second?
Not sure this is a good idea...

I have a scripts to [Notify on host up and down](https://git.eworm.de/cgit/routeros-scripts/about/doc/netwatch-notify.md) (and optionally run hooks/scripts), but the basic idea is to have a state machine to delay actions and mitigate false positives.

As I have nothing appropriate and you already [opened a thread on forums](https://forum.mikrotik.com/viewtopic.php?t=187461)... Closing.

**Comment by Jason-MK** [comment]
> 

Hello @eworm-de 

I want to know just an answer for a simple question , 

So all what I need to install the script or copy it to the scripts but then how do I added one of the hosts ? 

best regards

**Comment by eworm-de** [comment]
You need to read the documentation.

**Comment by taahgraham** [comment]
You would be looking for a simple icmp script, point it at the default
gateway of remote end-point 👍
