### ISSUE TITLE
Script syntax broken. not compatible with ROS v6.49.7

### ISSUE THREAD

**Issue by crowfeatherjoe** [eworm-de/routeros-scripts#38]
Forward slashes for elements inside RouterOS are deprecated. For example: `/system/routerboard/print` no longer functions, the proper syntax is now `/system routerboard print`

for this reason, the entire script system is unusable on ROS v6.49.7

**Comment by eworm-de** [comment]
Sure, use this:
https://git.eworm.de/cgit/routeros-scripts/about/?h=routeros-v6
