### ISSUE TITLE
64k limit problem for "tool fetch url"

### ISSUE THREAD

**Issue by katanatr** [eworm-de/routeros-scripts#51]
If the size of the IP list in the URL for the fw-addr-lists list is larger than 64k, it cannot download all of it. It can download the first 64k size. Can you do a looped download in parts for this, @eworm-de?

For example, can you download the entire content in parts like this with a loop?
`:tool fetch url=$url http-header-field="Range: bytes=$start-$end" output=user defined`

**Comment by eworm-de** [comment]
Yes, that is a limitation in RouterOS... Please make sure to open a support issue at Mikrotik and ask to address this. I did myself (SUP-132297) and answer was:

> If there will be similar requests, we will consider increasing the output limit.

I am hesitating to do the loop thing... It makes the code fragile, and not all servers do support it. (In fact a lot of servers are configured not to support this, or do not support it if content is generated on request.)
