### ISSUE TITLE
 Add html support to notification telegram

### ISSUE THREAD

**Issue by DakingRT** [eworm-de/routeros-scripts#54]
Hi,
This is a suggestion, would it be possible to add html support to the notification telegram bot in the future? Now it is only possible to send in markdown format and forcing the body to be in a code box.

Greetings

**Comment by eworm-de** [comment]
The scripts support several types of sending notifications, namely E-Mail, Matrix, Ntfy and Telegram. All these do send the same notification, so the best I can do is basic formatting with indention. 

Where possible I make the client show the content with fixed width font then. For Telegram that is using the blocks...

Everything else would be a maintenance burden I can not handle. I would have to format every single notification for every type... So no, unless you have a way to handle this with minimal extra cost.
