### ISSUE TITLE
check-routeros-update and other similar scripts suggested scheduler time

### ISSUE THREAD

**Issue by bubenkoff** [eworm-de/routeros-scripts#56]
In the check-routeros-update script's docs, it's suggested to use the 'startup' time of the script to be scheduled.
For such actions, it seems more logical to schedule it at night instead, as the update shouldn't normally happen in the busy time.

**Comment by eworm-de** [comment]
The primary intend here is to notify the user on update. If device is configured to install updates automatically it may make sense to schedule at night. You are free to change that to your needs.

**Comment by bubenkoff** [comment]
Still IMO changing the suggested time to the night would serve both
purposes just fine.

**Comment by eworm-de** [comment]
Hmm, we have a mechanism to schedule the reboot at night... Perhaps we should just add a confirmation option to always schedule the reboot on automated update?

**Comment by bubenkoff** [comment]
Do you mean to schedule it with this change, instead of directly rebooting?

**Comment by bubenkoff** [comment]
Ok, thanks for the clarification.
I think it makes a lot of sense to implement it this way indeed.

**Comment by eworm-de** [comment]
Pushed changes to the `next` branch... Do you want to give it a try?

**Comment by bubenkoff** [comment]
Yes, please!

**Comment by bubenkoff** [comment]
@eworm-de the router got autoupdated last night, and the ```:global PackagesUpdateDeferReboot true;``` in the config didn't seem to defer the upgrade, it seemed to reboot right away when the script was scheduled (2 am).
Is it a good idea to add some logging so that we can see that the defer really happens?

**Comment by eworm-de** [comment]
There is logging, it gives something like:
```
script,info packages-update: Scheduled reboot for update at 03:25:44 local time (Europe/Berlin).
```
And it works for me.

**Comment by bubenkoff** [comment]
Ok thanks, maybe I've missed it indeed, as I only have a memory log there.
I think I'll add packages-update to the log forwarding to monitor it better.
