### ISSUE TITLE
ADD username/password auth for ntfy

### ISSUE THREAD

**Issue by gionag** [eworm-de/routeros-scripts#59]
Hello !
can you provide a way to specify username and password for ntfy ?
fetch can accomodate user, pass for that.

some private ntfy instances (self-hosted) can be secured by that

thanks

**Comment by eworm-de** [comment]
I do not have access to that for testing.

**Comment by gionag** [comment]
i will test on my side and make a pull req

**Comment by eworm-de** [comment]
This is just *basic auth*, no? Wondering if giving credentials with the domain works... Can you try something like "`username:password@domain`"?

**Comment by eworm-de** [comment]
Ping... Any chance you test this?

Note to self... This is the documentation on authentication: https://docs.ntfy.sh/publish/#authentication

**Comment by gionag** [comment]
tested.
works perfectly !
good job and nice addition.

(the more i use your scripts ecosystem more i like them, keep it up !)

**Comment by eworm-de** [comment]
Great, thanks for testing!
