### ISSUE TITLE
Failed Telegram Notification

### ISSUE THREAD

**Issue by gionag** [eworm-de/routeros-scripts#60]
Testing the telegram notification.
triple checked bot chatId and BotToken, they are correct.
postman works with that parameters.

notification is queued and never received.

i can see that it is downloading a GOdaddy cert, CRL is in red.

![image](https://github.com/eworm-de/routeros-scripts/assets/1058123/d84de561-05f5-42fb-8d6a-5d350de33fde)
![image](https://github.com/eworm-de/routeros-scripts/assets/1058123/6d2b4dd1-4bde-4601-8dd5-693428b3269e)

have you recently tested it ?

**Comment by eworm-de** [comment]
I use it all the time, so absolutely sure the code works.

CRL is not used, as it causes too much trouble. All my scripts run `fetch` with `check-certificate=yes-without-crl`.

Does this give the expected output?

```
:put $TelegramTokenId;
:put $TelegramChatId;
```

**Comment by eworm-de** [comment]
Anything in logs that gives a clue? Running `fetch` always leaves some messages there.

**Comment by gionag** [comment]
> I use it all the time, so absolutely sure the code works.
> 
> CRL is not used, as it causes too much trouble. All my scripts run `fetch` with `check-certificate=yes-without-crl`.
> 
> Does this give the expected output?
> 
> ```
> :put $TelegramTokenId;
> :put $TelegramChatId;
> ```
```
:put $TelegramChatId;      
3#######8
:put $TelegramTokenId;     
###########:AAAAAAAAAAAAA_BBBBBBBBBBBBBBBBBBBBBBBB
```

in logs i have 

`fetch,info Download from api.telegram.org FAILED: Fetch failed with status 400`

if i ping api.telegram.org it pings, and resolve to the correct ip

The bot is not a member of any group. and the option i have set in "globa-config-overlay" are just
```
:global TelegramTokenId "TOKEN_ID_AS_ABOVE";
:global TelegramChatId "CHAT_ID_AS_ABOVE";
```

What else could i check ?

**Comment by gionag** [comment]
> Just to be sure, as not visible from your output... Your token does not start with "bot", no? That belongs to the url and is added automatically.

indeed is not.

**Comment by eworm-de** [comment]
Running out of ideas... Please double-check there's no typo, missing or extra character. It's no more than these two variables.

**Comment by eworm-de** [comment]
Any news on this? Did you figure?

**Comment by gionag** [comment]
it solved itself. 
So i haven't figured it out.
nothing was changed on my side... maybe an auto update of the script has changed some sub-section that was key to make it work.

**Comment by eworm-de** [comment]
Hmm, there were no changes related to Telegram notifications... No idea what happened then.

Anyway, closing the issue.
