### ISSUE TITLE
How to write a script to obtain WiFi signals and snr？

### ISSUE THREAD

**Issue by ggsnpdsn** [eworm-de/routeros-scripts#65]
There are two devices A (working in AP Bridge mode) and device B (working in Station Bridge mode), and I want device A to obtain real-time signal strength from device B and send it to the designated server. Device B obtains the signal strength of device A in real-time and sends it to the designated server.
Can the script implement this feature? What should we do?

**Comment by eworm-de** [comment]
Scripts can do a lot, though wondering if SNMP suits better.
Anyway... This is out of scope for my scripts, so closing.
