### ISSUE TITLE
Backup Upload via SFTP not working

### ISSUE THREAD

**Issue by rpchan44** [eworm-de/routeros-scripts#77]
global-config-overlay

:global BackupRandomDelay "30";
:global BackupUploadUrl "sftp://192.168.99.4/";
:global BackupUploadUser "z1";
:global BackupUploadPass "p@ssw0rd23";

Using normal SFTP i was able to upload file using "z1" as user

This is the error has been log in MT during backup script execution

Upload to 192.168.99.4 FAILED: closing connection: \<permission denied\> 192.168.99.4:22 (6) (6)

on 192.168.99.4 /etc/ssh/sshd_config I append the following section

Match User z1
    AuthenticationMethods password

This was tested on v7.15.2 thanks a lot much appreciate it!!

![failed](https://github.com/user-attachments/assets/48d426b1-3846-48d5-ac7d-bd1b45b72a0f)

**Comment by eworm-de** [comment]
Hmm, not absolutely sure, but "`permission denied`" sounds like file permission... So I guess the authentication succeeded, but file could not be written. Possibly you missed the remote path or the destination folder is not writable? Any logs from the server that indicate what the issue could be?

**Comment by rpchan44** [comment]
Thanks for your prompt reply, I was confused too
![success](https://github.com/user-attachments/assets/9dffc4ea-e065-49b4-bff2-a50a94a85e79)

**Comment by eworm-de** [comment]
Not sure if implementations differ in handling of default directory. You could try:
```
:global BackupUploadUrl "sftp://192.168.99.4/home/z1/";
```
Does that work?

**Comment by rpchan44** [comment]
Yes that fixed it!!!! the sftp client implementation from mikrotik is flawed? anyway thanks a lot for your great effort!! please close this now

**Comment by eworm-de** [comment]
No, it's ok - it just expects the complete path.

Have a look at your screenshots... For `scp` your added `~` which is equivalent to `/home/z1/` here. The interactive `sftp` just opens at the home directory automatically.
