### ISSUE TITLE
fw-addr-lists - Certificat for spamhaus.org/drop/drop.txt is invalid

### ISSUE THREAD

**Issue by BadFlo** [eworm-de/routeros-scripts#78]
https://github.com/eworm-de/routeros-scripts/blob/90632f223adce7139b831fc2e6a0668431e5f26c/global-config.rsc#L109

Could you update the certificat ?

Also, spamhaus has droped edrop file and migrated to json format, is there any chance you could add an option to parse JSON format ? It's the only format for IPv6 from spamhaus.

Thanks in advance.

**Comment by eworm-de** [comment]
Updated... Though this is just commented. So you have to change this in your configuration overlay as well.

Currently JSON is not supported here... Technically it would be possible I guess. Feel free to open a new issue to track this.
