### ISSUE TITLE
Telegram notifications failure

### ISSUE THREAD

**Issue by sergiobaiao** [eworm-de/routeros-scripts#80]
Hi there,

After working flawless for several weeks, my telegram notification script is failing now with this:

Download from api.telegram.org FAILED: 401 should contain www-authenticate header

what should i do?

**Comment by eworm-de** [comment]
Hmm, very interesting... I have not seen something like that with Telegram API and I can not reproduce.

Just wondering is there a proxy between your Mikrotik device and the Telegram servers that requires authentication?

**Comment by eworm-de** [comment]
Oh, and please check that variables (`TelegramTokenId` and `TelegramChatId`) are properly set and populated. An internal process crashing could clear these.

**Comment by eworm-de** [comment]
No answer, so closing for now.
